"""Headed

Revision ID: 31608a667ed0
Revises: 46dffedbbce7
Create Date: 2022-05-20 17:08:41.229417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31608a667ed0'
down_revision = '46dffedbbce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('trial_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_str')
    op.drop_column('users', 'image_url')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
