name: Build and Deploy Code

on:
  push:
    branches:
      - "master"

jobs:
  job1:
    env:
      DATABASE_HOSTNAME=localhost
      DATABASE_PORT=5432
      DATABASE_PASSWORD=trialandError
      DATABASE_NAME=fastapi
      DATABASE_USERNAME=postgres
      SECRET_KEY=froıfk32ok*kefmssdlkmcd1%+%U/YHsfdgerf!
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=60
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Say hello world
        run: echo "Hello World"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip instal --upgrade pip
      - name: install all dependencies
        uses: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -v -s



